//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotecas.Dalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public string rut { get; set; }
        public string patente { get; set; }
        public string ruta { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int codigo { get; set; }
    
        public virtual Peaje Peaje { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
